### ISSUE TITLE
画面が変わる時にエラーでアプリが落ちちゃいます

### ISSUE THREAD

**Issue by 1113kaito** [1113kaito/Action#3]
![2017-07-24 10 44 32](https://user-images.githubusercontent.com/30278613/28505282-40ac0a34-705d-11e7-9e9f-f63dd618db08.png)
![2017-07-23 23 26 49](https://user-images.githubusercontent.com/30278613/28505286-4a5d0baa-705d-11e7-86ec-04e856a069b4.png)

**Comment by halu5071** [comment]
エラー画面のところで
`Caused by` って書かれているところが大事だから、そこのスクショも載せてみて！

**Comment by 1113kaito** [comment]
Caused by って書かれているところはどこにありますか

**Comment by halu5071** [comment]
エラーが起きたときに、AndroidMonitorを見ればいいよ！

**Comment by 1113kaito** [comment]
これですか？
![2017-07-24 21 32 09](https://user-images.githubusercontent.com/30278613/28523475-99951640-70b7-11e7-8331-42f031dfb94d.png)

**Comment by halu5071** [comment]
そう！
でもできるなら、全部見せてほしい！

**Comment by 1113kaito** [comment]
画面全体ってことですか？

**Comment by halu5071** [comment]
エラー画面の全体ね、見せてほしい
と言うか、コピーしてここに貼り付けてもいいよ

**Comment by 1113kaito** [comment]
```
Caused by: java.lang.reflect.InvocationTargetException
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
                                                                     at android.view.View.performClick(View.java:5610) 
                                                                     at android.view.View$PerformClick.run(View.java:22260) 
                                                                     at android.os.Handler.handleCallback(Handler.java:751) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                  Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {io.keiji.action/io.keiji.action.MainActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
                                                                     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
                                                                     at android.app.Activity.startActivityForResult(Activity.java:4224)
                                                                     at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
                                                                     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:77)
                                                                     at android.app.Activity.startActivityForResult(Activity.java:4183)
                                                                     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                     at android.app.Activity.startActivity(Activity.java:4507)
                                                                     at android.app.Activity.startActivity(Activity.java:4475)
                                                                     at io.keiji.action.StartActivity.start(StartActivity.java:28)
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
                                                                     at android.view.View.performClick(View.java:5610) 
                                                                     at android.view.View$PerformClick.run(View.java:22260) 
                                                                     at android.os.Handler.handleCallback(Handler.java:751) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

**Comment by halu5071** [comment]
僕の環境では実行できたよん
[bullheadN2G47Zhoriiyasunori07252017085734.mp4.zip](https://github.com/1113kaito/Action/files/1171555/bullheadN2G47Zhoriiyasunori07252017085734.mp4.zip)
なので、左のカラムにある
`.gradle`
っていうファイルを一回削除して、下の画像のように緑のぐるぐるマークを押してみて
![20187355_1326153580830934_2123376766_o](https://user-images.githubusercontent.com/18444125/28549794-a581ed7e-7117-11e7-809d-7b89caa445d7.png)

**Comment by 1113kaito** [comment]
gradleを一回削除して画像のボタン押したんですけどやっぱりエラーです

**Comment by halu5071** [comment]
ちなみに、いまGithubにあるコードに変更は加えた？？もし変更があるなら、AndroidStudio上でファイルが青くなってると思うんだけど。

**Comment by 1113kaito** [comment]
多分変更を加えました

**Comment by halu5071** [comment]
それなら、その分をGithubにPushしてみて。
やり方は覚えてるかな？？

**Comment by 1113kaito** [comment]
なんかPushにHEADってやつしかなくて
![2017-07-25 16 16 10](https://user-images.githubusercontent.com/30278613/28560222-ba6dc612-7154-11e7-83a4-9ecf894f32da.png)

**Comment by halu5071** [comment]
それなら、
①上にあるタブから、「ブランチ」をクリック
②「新規ブランチ」をクリック
③ブランチ名に「master」を入力
④「ブランチを作成」をクリック
これでやってみ。

**Comment by 1113kaito** [comment]
できました

**Comment by halu5071** [comment]
Good Job!!
実機ではうまくいったかな？？

僕はまだ出先だから、こっちで動作確かめられないんよ。でもパッと見大丈夫そう。

**Comment by halu5071** [comment]
ん、起動したときに最初に実行される`Activity`が`LastActivity`になってるけど、大丈夫かな？？

**Comment by 1113kaito** [comment]
どこですか？

**Comment by halu5071** [comment]
`AndroidManifest.xml`のところ。起動したときのアクティビティが`LastActivity`になってる

**Comment by halu5071** [comment]
`AndroidManifest.xml`の理解は大丈夫かな？？
解説記事見つけたよん
http://programming-study.com/technology/android-manifest/
